### PR TITLE
refactor(extension): change styles for side panel button component

### PR DESCRIPTION
**Pull request by jplorek-atix**
# Checklist

- [x] JIRA - \<[LW-7105](https://input-output.atlassian.net/browse/LW-7105)>
- [x] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Restyle the side panel button component

## Screenshots

https://github.com/input-output-hk/wallet-world/assets/65184652/2c9dcb84-f3f9-49ec-ab71-9acac8ad6491

https://github.com/input-output-hk/wallet-world/assets/65184652/c375b29a-2a8e-443e-8e53-ac55b7253b4b

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/583/5346673003/index.html) for [71774005](https://github.com/input-output-hk/lace/pull/58/commits/71774005b19a0db16dd3b777fdc71c6327c09d3f)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 36     | 0      | 0       | 0     | 36    | ✅     |

[LW-7105]: https://input-output.atlassian.net/browse/LW-7105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by marcin-mazurek — APPROVED** [review]

**Comment by allanleone** [comment]
Sorry, it could be possible to change the arrow animation for something more smooth? maybe just an intro animation (repeated once)

I will prepare a video/HTML based on the latest figma layout to better illustrate: https://www.figma.com/file/RPN3V4Et7hMbXkV5ZIF75i/Lace-UI---Browser?type=design&node-id=17762-321424&t=SKQfnOEbAj0PzTlO-4

**Comment by allanleone** [comment]
I'm adding an updated version of the button animation -- gif/video attached 

- "bouncing" effect removed & replaced by a "slide-in effect (no-repeat)"
- arrow size adjustment (to make the prototype match figma)
- inner borders removed during transition (hover/in-out)



https://github.com/input-output-hk/lace/assets/8201486/3ada6d88-4194-483a-9bec-7dfae77e83a3

**Comment by jplorek-atix** [comment]
> I'm adding an updated version of the button animation -- gif/video attached
> 
> * "bouncing" effect removed & replaced by a "slide-in effect (no-repeat)"
> * arrow size adjustment (to make the prototype match figma)
> * inner borders removed during transition (hover/in-out)
> 
>  2023-06-21.11-53-52.mp4

@allanleone I've addressed these issues


https://github.com/input-output-hk/lace/assets/65184652/1f776b5d-f27f-4ade-809c-9fcfd4c26506

**Comment by milagi** [comment]
@jplorek-atix 'Normal' button in dark mode isn't correct. The right section is gray when it should be black:
Actual:
image


Expected:
image

**Comment by marcin-mazurek** [comment]
Looking good :) I'll approve once @milagi comments are resolved :)

**Review by milagi — APPROVED** [review]

**Review by DominikGuzei — APPROVED** [review]

**Pull request merged**
