### PR TITLE
Feat: Adds payment keys comparison to handle owner verification

### PR DESCRIPTION
**Pull request by VanessaPC**
# Checklist

- [x] JIRA - LW-7559
- [x] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution
Extract payment credentials and include it in verifying ownership of the user handles. 

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1166/5678439075/index.html) for [4c185693](https://github.com/input-output-hk/lace/pull/298/commits/4c1856934b8fb390c5e123f52d4f92cb10c16bd5)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 35     | 0      | 0       | 0     | 35    | ✅     |

### CODE REVIEW

**Review by rhyslbw — COMMENTED** [review]
Right now it's hard to see what's changed since the diff is not very helpful after repositioning of the custom error type code. Can you separate this into an initial refactor commit before I review?

**Review by greatertomi — APPROVED** [review]

**Review by rhyslbw — APPROVED** [review]
LGTM! Nice work @VanessaPC

**Comment by gabriela-ponce** [comment]
@VanessaPC I can reproduce this issue on the latest build

- Add the handle as a contact on the address book, send the handle from one address to the other, and then, validate the address book again.
**Result:** I see the alert that the address has changed but it is the same wallet.
[Check this video](https://drive.google.com/file/d/1YQxXN_seTM73AWkMjOZQu1iNVIBlTMq2/view?usp=drive_link) (**dark theme:** running `main` branch to use multi delegation, **white theme**: running the latest artifacts from this PR)

**Comment by rhyslbw** [comment]
@mkazlauskas will write a utility in the SDK for introspecting the keys from a given address, as there's a couple of edge cases we need to cover, and there's sufficient complexity to make it valuable as an upstream utility.

**Pull request merged**
