### PR TITLE
fix(extension): [LW-11508] only display banxa popup on mainnet

### PR DESCRIPTION
**Pull request by mchappell**
# Checklist

- [ ] JIRA - [LW-11508](https://input-output.atlassian.net/browse/LW-11508)

Checks
- CTA hidden if not connected to mainnet
- CTA hidden if feature not enabled

Switching to use the wallet store over the settings context ensures that the component gets the updated chain type as soon as the user switches chains. Using the app settings context should only be used within the settings pages

[LW-11508]: https://input-output.atlassian.net/browse/LW-11508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pczeglik-iohk** [comment]
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!



**processReports**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6932/10833400684/index.html) for [f85ad41f](https://github.com/input-output-hk/lace/pull/1427/commits/f85ad41fd7182275af8a611bce1a3b8f56d64868)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 31     | 1      | 4       | 0     | 36    | ❌     |

**Review by rhyslbw — CHANGES_REQUESTED** [review]
Best to write a descriptive commit message to explain what's happening here. As a reviewer I'm having to guess at why some logic, that looks fairly innocuous, needs fixing 😄

**Comment by mchappell** [comment]
@rhyslbw in lieu of updating the commit message here i've updated the description. I'll add similar notes to the commit message upon squashing + merging

**Review by rhyslbw — APPROVED** [review]
Nice work @mchappell 💪

**Pull request merged**
