### PR TITLE
fix: remove unused onboarding components

### PR DESCRIPTION
**Pull request by greatertomi**
# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

### CODE REVIEW

**Review by pczeglik-iohk — COMMENTED** [review]
How did you determine what are old onboarding components @greatertomi?

**Comment by pczeglik-iohk** [comment]
Is this PR part of some existing JIRA ticket? Is @ljagiela going to test this?

**Comment by greatertomi** [comment]
> How did you determine what are old onboarding components @greatertomi?

These components are not used anywhere.

**Comment by greatertomi** [comment]
> Is this PR part of some existing JIRA ticket? Is @ljagiela going to test this?

It is not part of any ticket. @ljagiela can test it. Do I need to create a ticket for this?

**Comment by pczeglik-iohk** [comment]
> > Is this PR part of some existing JIRA ticket? Is @ljagiela going to test this?
> 
> It is not part of any ticket. @ljagiela can test it. Do I need to create a ticket for this?

I have no idea to be honest. Maybe if e2e tests pass we are good.

Lets maybe see what is the expectation for @szymonmaslowski [PR](https://github.com/input-output-hk/lace/pull/1173)

**Review by szymonmaslowski — APPROVED** [review]

**Review by pczeglik-iohk — APPROVED** [review]

**Pull request merged**
