### PR TITLE
fix(extension): reset user analytics status when wallet is removed

### PR DESCRIPTION
**Pull request by jplorek-atix**
# Checklist

- [ ] JIRA - \<[LW-8122](https://input-output.atlassian.net/browse/LW-8122)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

When the wallet was removed the `optedInForEnhancedAnalytics` state in `AnalyticsProvider/context.tsx` was never set to its default value again. Because of this, the effect that is calling `analyticsTracker.setOptedInForEnhancedAnalytics(optedInForEnhancedAnalytics)` was never triggered after the user accepts analytics again, since `optedInForEnhancedAnalytics` never changed the previous value (ACCEPTED)

To solve this, a listener to the current route path is added, so, when the user is redirected to `/setup`, we can reset the state of `optedInForEnhancedAnalytics` to `REJECTED`

[LW-8122]: https://input-output.atlassian.net/browse/LW-8122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1773/6016681932/index.html) for [28ccbab7](https://github.com/input-output-hk/lace/pull/430/commits/28ccbab75de4f01e3a49cf155329d58acf33e9af)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 3      | 0       | 0     | 35    | ❌     |

### CODE REVIEW

**Review by DominikGuzei — APPROVED** [review]
Great catch, simple solutuion 👍

**Review by marcin-mazurek — COMMENTED** [review]
From what I remember, we should be handling this in [useWalletManager hook](https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/hooks/useWalletManager.ts#L299) - can you check why is it not working?

**Review by marcin-mazurek — APPROVED** [review]
I'm still not 100% happy 😄 With this approach, we have some leaky abstraction - I think that `AnalyticsProvider` shouldn't necessarily be aware of Settings module. But it's probably the easiest solution we can do without larger refactoring, so let's go with it for now, but let's review it after the release and see how we could improve it.

**Comment by marcin-mazurek** [comment]
@bslabiak can you re-test it please?

**Review by bslabiak — APPROVED** [review]

**Pull request merged**
