### PR TITLE
chore: LW-9786 enable single pool delegation in multi-delegation view

### PR DESCRIPTION
**Pull request by tomislavhoracek**
# Checklist

- [x] https://input-output.atlassian.net/browse/LW-9786

---

## Proposed solution

This PR introduces an additional check where we enabled single pool delegation in multi-delegation view. This check will allow users with older Ledger Cardano App and Trezor Firmware ( multi-delegation not supported ) to delegate in a single pool even in multi-delegation view.
Also, this PR fixes HW multi-delegation tx signing.

## Testing
-  Check if single and multi delegation works when you are using devices with the latest Ledger Cardano App and Trezor Firmware
-  Check if single pool delegation works when you are using devices with older Ledger Cardano App and Trezor Firmware

### CODE REVIEW

**Review by DominikGuzei — APPROVED** [review]
Great work 🎉

**Review by VanessaPC — APPROVED** [review]

**Review by AngelCastilloB — APPROVED** [review]
LGTM @tomislavhoracek

**Comment by tomislavhoracek** [comment]
@DominikGuzei @VanessaPC @AngelCastilloB Could you please check my last commit: [d0824cf](https://github.com/input-output-hk/lace/pull/970/commits/d0824cffe0875f7a66ff4f60994cc95e07782ef3) ? 🙏

**Comment by DominikGuzei** [comment]
@tomislavhoracek LGTM 🚢

**Comment by tomislavhoracek** [comment]
@DominikGuzei you just left "approval" comment, can you approve the PR 🙏

**Review by szymonmaslowski — APPROVED** [review]
LGTM

**Review by DominikGuzei — APPROVED** [review]

**Pull request merged**
