### PR TITLE
feat: create documentation for the transaction JSON file structure

### PR DESCRIPTION
**Pull request by greatertomi**
# Checklist

- [x] JIRA - LW-10680
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Create documentation for the transaction JSON file structure

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

### CODE REVIEW

**Comment by pczeglik-iohk** [comment]
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!



**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6011/9764013535/index.html) for [b092397a](https://github.com/input-output-hk/lace/pull/1261/commits/b092397ad30ad9efd1920a824eaa791187306255)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 0       | 0     | 33    | ✅     |

**Review by danielmain — CHANGES_REQUESTED** [review]
@greatertomi where are the cosigner signatures? What about adding a section for them?

```
    "signatures": {
      "type": "array",
      "description": "List of cosigners and their signatures",
      "items": {
        "type": "object",
        "properties": {
          "cosigner": {
            "type": "string",
            "description": "The public key of the cosigner"
          },
          "signature": {
            "type": "string",
            "description": "The signature provided by the cosigner"
          }
        },
        "required": ["cosigner", "signature"]
      }
    },
```

**Comment by greatertomi** [comment]
> @greatertomi where are the cosigner signatures? What about adding a section for them?
> 
> ```
>     "signatures": {
>       "type": "array",
>       "description": "List of cosigners and their signatures",
>       "items": {
>         "type": "object",
>         "properties": {
>           "cosigner": {
>             "type": "string",
>             "description": "The public key of the cosigner"
>           },
>           "signature": {
>             "type": "string",
>             "description": "The signature provided by the cosigner"
>           }
>         },
>         "required": ["cosigner", "signature"]
>       }
>     },
> ```

I learned that CBOR contains the witness set or cosigners, and you can get them by doing something like this. There's more discussion on this [here](https://input-output-rnd.slack.com/archives/C070F9SSG59/p1719830314585689?thread_ts=1719570794.213119&cid=C070F9SSG59)

```ts
Serialization.Transaction.fromCbor(cbor).toCore().witness.scripts
```

**Review by szymonmaslowski — APPROVED** [review]
GJ! Could you move this file to the src/shared-wallets/docs, please?

**Review by danielmain — APPROVED** [review]

**Review by danielmain — APPROVED** [review]

**Pull request merged**
