### PR TITLE
feature(staking): lw-7093 multi staking popup view

### PR DESCRIPTION
**Pull request by szymonmaslowski**
# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-7093)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Staking popup view implementation according to designs: [figma](https://www.figma.com/file/C1g4ndWSv5u53GMlTeQ0nN/Lace-Browser---Pop-up-view-UI-Design?node-id=215%3A67546&mode=dev)

## Testing

Open popup and go to staking

## Screenshots

image
image
image
image
image

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1462/5852366385/index.html) for [2d34c344](https://github.com/input-output-hk/lace/pull/361/commits/2d34c34414f00a2f8e746663f7a916e7eb94f8bd)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 34     | 1      | 0       | 0     | 35    | ❌     |

### CODE REVIEW

**Review by przemyslaw-wlodek — APPROVED** [review]

**Comment by ManusMcCole** [comment]
hI @szymonmaslowski. Good work so far. i noticed a small issue where Staking and Your Pools text is almost invisible in dark mode. See [screenshot](https://drive.google.com/file/d/1iDGTSa4sVKbco10dVai3Zxac6m38QrUv/view?usp=sharing) and [screenshot](https://drive.google.com/file/d/1rIpu2n0sBZgFQYDWt6yEoR_cH2oomMSK/view?usp=sharing). Also some of the text in the pools overview screen for last rewards is overflowing out of the box. See [screenshot](https://drive.google.com/file/d/1bufwLIfwOIVyqIbvldn2aDhGbBe1DcyM/view?usp=sharing)

**Comment by szymonmaslowski** [comment]
> 



> hI @szymonmaslowski. Good work so far. i noticed a small issue where Staking and Your Pools text is almost invisible in dark mode. See [screenshot](https://drive.google.com/file/d/1iDGTSa4sVKbco10dVai3Zxac6m38QrUv/view?usp=sharing) and [screenshot](https://drive.google.com/file/d/1rIpu2n0sBZgFQYDWt6yEoR_cH2oomMSK/view?usp=sharing). Also some of the text in the pools overview screen for last rewards is overflowing out of the box. See [screenshot](https://drive.google.com/file/d/1bufwLIfwOIVyqIbvldn2aDhGbBe1DcyM/view?usp=sharing)

Hey @ManusMcCole, Thanks for rising those problems. I fixed styling of headers. For the issue of last rewards overflowing that is gonna be fixed by the task I am currently working on, so let's remember that and check in my next PR 😉

**Comment by ManusMcCole** [comment]
Hi @szymonmaslowski. Good job on the fixes.All looks good now except for the Start Staking screen is blank. Is this expected ? See [screenshot](https://drive.google.com/file/d/1p_M8qy86jYKXZ9f2mEH-icinYztb53kF/view?usp=sharing)

**Comment by szymonmaslowski** [comment]
> Hi @szymonmaslowski. Good job on the fixes.All looks good now except for the Start Staking screen is blank. Is this expected ? See [screenshot](https://drive.google.com/file/d/1p_M8qy86jYKXZ9f2mEH-icinYztb53kF/view?usp=sharing)

That is expected for now. @mrcnk is just about to add the proper UI for this case, but he is waiting for this PR to be merged.

**Review by ManusMcCole — APPROVED** [review]
Good work @szymonmaslowski

**Pull request merged**
