### PR TITLE
feat(extension): add Token Information section in token details

### PR DESCRIPTION
**Pull request by lgobbi-atix**
# Checklist

- [x] JIRA - LW-4865
- [x] Screenshots added.

---

## Proposed solution

- Add new "Token Information" section in the token details drawer to display and copy the token's fingerprint and policy ID.
- Add separators between the different sections of the token details
- Remove the "See all your transactions" button from the "Recent Transactions" section in the popup view and replace it with a "View All" link next to the section title, aligning with the browser view.
- Limit the amount of recent transactions shown for a token in the browser view to 3 from 10.
- Add new prop to `InlineInfoList` items to be able to display a copy icon on hover

## Screenshots

image

image

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1960/6110667562/index.html) for [c6c7e651](https://github.com/input-output-hk/lace/pull/414/commits/c6c7e6517cb92a021b96c149b5dd8219654689a5)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 28     | 4      | 0       | 0     | 32    | ❌     |

### CODE REVIEW

**Review by mchappell — APPROVED** [review]

**Review by miorsufianiohk — CHANGES_REQUESTED** [review]
Hi @lgobbi-atix ,

As discussed on Slack, this requirement has not been satisfied yet:
```
When clicking it, redirect the user to Cexplorer for both Fingerprint and PolicyID
Open a new tab in the same window to display Cexplorer
```

**Comment by lgobbi-atix** [comment]
> Hi @lgobbi-atix ,
> 
> As discussed on Slack, this requirement has not been satisfied yet:
> 
> ```
> When clicking it, redirect the user to Cexplorer for both Fingerprint and PolicyID
> Open a new tab in the same window to display Cexplorer
> ```

Added here https://github.com/input-output-hk/lace/pull/414/commits/e715ba658a5b813041a4b53d497f38a257c8d73f

**Review by miorsufianiohk — CHANGES_REQUESTED** [review]
Hi @lgobbi-atix ,

Thank you for the new update.  However, when I clicked on both links, both **Fingerprint** and **Policy ID** pointed to the same Fingerprint URL, for example : https://preprod.cexplorer.io/asset/asset12756zyxkah5rmhzcxjvn0e7avzd3xwhskv422v

Actually, Policy ID has URL too, eg: https://preprod.cexplorer.io/policy/e16c2dc8ae937e8d3790c7fd7168d7b994621ba14ca11415f39fed72

Perhaps the link needs to point to the right URL for Policy ID?

Screenshot 2023-08-30 at 9 33 53 AM

**Comment by lgobbi-atix** [comment]
> Hi @lgobbi-atix ,
> 
> Thank you for the new update. However, when I clicked on both links, both **Fingerprint** and **Policy ID** pointed to the same Fingerprint URL, for example : https://preprod.cexplorer.io/asset/asset12756zyxkah5rmhzcxjvn0e7avzd3xwhskv422v
> 
> Actually, Policy ID has URL too, eg: https://preprod.cexplorer.io/policy/e16c2dc8ae937e8d3790c7fd7168d7b994621ba14ca11415f39fed72
> 
> Perhaps the link needs to point to the right URL for Policy ID?
> 
> Screenshot 2023-08-30 at 9 33 53 AM

The ticket is not really clear about it but it makes sense to me. Pushed a fix e986a8302abcd90e16b86965ba3c992535a38336

**Review by miorsufianiohk — APPROVED** [review]
Looking much better. Great job @lgobbi-atix . Approved! 👍

**Review by ljagiela — APPROVED** [review]

**Pull request merged**
