### PR TITLE
test(extension): update allure-publish-action and action-slack-notify

### PR DESCRIPTION
**Pull request by wklos-iohk**
# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

### CODE REVIEW

**Review by pczeglik-iohk — APPROVED** [review]
Code looks good. If you need approval @wklos-iohk you have mine :)

**Comment by pczeglik-iohk** [comment]
oh, I didn't notice it's still a draft :)

**Comment by wklos-iohk** [comment]
@pczeglik-iohk unfortunately tallure-publish-action does not work properly after update if some tests have failed: https://github.com/input-output-hk/lace/actions/runs/8647961385/job/23710670405

**Comment by wklos-iohk** [comment]
Closing as it was already covered in another PR

**Pull request closed without merging**
