### PR TITLE
fix: confirm button is now disabled if password is empty on staking confirmation screen

### PR DESCRIPTION
**Pull request by AngelCastilloB**
Password confirmation on Staking drawer gets stuck if you press confirm with empty password

# Checklist

- [x] JIRA - \<[link](https://input-output.atlassian.net/issues/LW-11405)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Component was not checking against the password component value. This is now fixed

### CODE REVIEW

**Comment by pczeglik-iohk** [comment]
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!



**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6943/10843466725/index.html) for [3560e39f](https://github.com/input-output-hk/lace/pull/1430/commits/3560e39f2f6bf240edc52ea66233bdc09a49c52c)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 4       | 0     | 36    | ✅     |

**Review by przemyslaw-wlodek — APPROVED** [review]
Awesome catch! 😄

**Review by greatertomi — APPROVED** [review]
Looks good to me

**Review by mchappell — APPROVED** [review]
Great work @AngelCastilloB

**Pull request merged**
