### PR TITLE
[LW-10451] Address book name broken on address input

### PR DESCRIPTION
**Pull request by lucas-barros**
# Checklist

- [x] JIRA - https://input-output.atlassian.net/browse/LW-10451
- [x] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Prevent line break on white spaces
- Add story to include scenario on snapshot test

## Testing

Create an address book entry with a white space such as "My address" and verify that the name is displayed correctly in send flow.

## Screenshots

image

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@lucas-barros In the core storybook i can see that the address book name doesn't look right (font color) on dark theme:
image

**Comment by lucas-barros** [comment]
> @lucas-barros In the core storybook i can see that the address book name doesn't look right (font color) on dark theme: image

That was due to switching from story with global theme to one with local theme. Fixed here: https://github.com/input-output-hk/lace/pull/1158/commits/75de21c9a48aeea74704e0295f487aebb8c82895.

**Review by renanvalentin — COMMENTED** [review]
LGTM

**Review by renanvalentin — APPROVED** [review]

**Review by VanessaPC — APPROVED** [review]
LGTM!

**Review by ljagiela — APPROVED** [review]

**Pull request merged**
