### PR TITLE
fix(staking): add pool to draftPortfolio when delegating all to 1

### PR DESCRIPTION
**Pull request by xdzurman**
# Checklist

- [x] [JIRA ](https://input-output.atlassian.net/jira/software/c/projects/LW/boards/1209?modal=detail&selectedIssue=LW-7942&assignee=5cfdfc4bc97d8b0c633413a7&assignee=UNASSIGNED_USER_ID)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

The pool was not being added to multi delegation draftPortfolio, therefore empty screen was shown. When staking all to 1 pool, follow the same procedure as if it was being added to a portfolio of pools and it was accepted instantly. From the code it looks like it was meant to be that way, just forgotten, @szymonmaslowski can you confirm?

## Testing

Find a wallet which never staked before, follow steps described by JIRA issue, and see that it works.

## Screenshots

Before:
image
After:
image

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1671/5960684666/index.html) for [bd01d6dd](https://github.com/input-output-hk/lace/pull/413/commits/bd01d6dd7474ea901ba6155edb2b18426ae8b809)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 2      | 0       | 0     | 35    | ❌     |

### CODE REVIEW

**Review by szymonmaslowski — APPROVED** [review]
Well spotted! Great job!

**Comment by ManusMcCole** [comment]
Hi Kamil. I was able to reproduce this on my end. See [video](https://drive.google.com/file/d/1jjkjLEZryX420zGZ_Lr9rr48En-2Spkb/view?usp=sharing)

**Comment by xdzurman** [comment]
Hello @ManusMcCole ! Hmmm that's strange, I tried the same thing on your video, and it works for me like this

https://github.com/input-output-hk/lace/assets/22454337/3f53c8df-a8e2-4315-b12b-68248bfef535

I tried updating the branch and built the app anew, can you please double check? Do you build the app locally, or get it from some CI storage?

**Comment by ManusMcCole** [comment]
Hi @xdzurman. Working now since main was merged 👍

**Review by ManusMcCole — APPROVED** [review]

**Review by refi93 — APPROVED** [review]

**Review by przemyslaw-wlodek — APPROVED** [review]

**Pull request merged**
